### ISSUE TITLE
Excuse me. Do you have got the unedited homework?

### ISSUE THREAD

**Issue by Josh00-Lu** [Meghat525/AI-for-Medicine#1]

**Comment by Meghat525** [comment]
Unedited homework?? Can you please elaborate.

**Comment by Josh00-Lu** [comment]
> Unedited homework?? Can you please elaborate.

the raw assignments I want to do it myself. But I cannot afford the course. So do you have the original assignments-copy?(there are some "None" in the notebook)

**Comment by Josh00-Lu** [comment]
That is the raw assignments. So do you have the original assignments?(there are some "None" in the notebook)

**Comment by Meghat525** [comment]
Sorry but I don't have the raw assignments.
